language: generic 
sudo: required
services:
  - docker
before_install
  - docker build -t sankarvm1/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sankarvm1/docker-react npm run test
